# Support the author by using the funding links below
# Developed and maintained by (OKESC) Alberto Romo Valverde with the help of awesome contributors.
# GitHub Sponsors: https://github.com/sponsors/OKESC
# Buy Me a Coffee: https://coff.ee/okesc

github: OKESC
buy_me_a_coffee: OKESC

# Your support means a lot to me to continue the development of open source project like this.
# Sponsoring this project means a lot to me. Your support helps me to building great open source projects just like this.